### ISSUE TITLE
z2pack for broken time reversal symmetry and SOC calculation 

### ISSUE THREAD

**Issue by SaranshaM** [Z2PackDev/Z2Pack#205]
Respected Sir,

I want to know, can we use z2pack for systems having broken time reversal symmetries with SOC calculations ? i could not find any example mentioning the the above fact.  I encounter the following error 

"Traceback (most recent call last):
  File "my_tb.py", line 20, in <module>
    print(z2pack.invariant.z2(result))
  File "/home/saransha/.local/lib/python3.8/site-packages/z2pack/invariant.py", line 54, in z2
    raise ValueError(
ValueError: The given WCC are not degenerate Kramers pairs at the edges of the surface."

Looking forward to your kind response. Thanking you. 

Saransha

**Comment by greschd** [comment]
The hybrid Wannier charge center evolution and Chern number calculations in Z2Pack can be used with any system, irrespective of symmetry.

However, for the Z2 invariant [1], the invariant is well-defined only when time-reversal symmetry is present. For this reason, the z2pack.invariant.z2 call checks that the Wannier charge centers are doubly degenerate at the edges of the surface.

So, the general answer is: yes, Z2Pack can be used without time-reversal symmetry. However, only invariants which are well-defined in the context of the symmetry of the system can be computed.

Best regards,
Dominik

[1] this is the 2D Kane-Mele Z2 invariant
