### ISSUE TITLE
Issue running 'fp/Bi_vasp' 

### ISSUE THREAD

**Issue by dptru10** [Z2PackDev/Z2Pack#75]
I am in the process of learning how to use Z2Pack to determine topological invariance in complex systems and as a first exercise was trying to run various examples and tutorial problems included in the Z2Pack developers package. I have installed the package via the GitHub developers package (python3 setup.py install) and linked Wannier90-1.2 via the Z2Pack website to my Vasp (Vasp 5.4.4, also tested Vasp 5.4.1 with same error) installation and tested to make sure Vasp is working with Wannier90 explicitly. However when I run the ‘Bi_vasp’ example I generate the following error, 

+----------------------------------------------------------------------+
|===================                                                   |
|SURFACE CALCULATION                                                   |
|===================                                                   |
|starting at 2018-12-14 15:18:53,080                                   |
|running Z2Pack version 2.1.1                                          |
|                                                                      |
|gap_tol:            0.3                                               |
|init_result:        None                                              |
|iterator:           range(8, 27, 2)                                   |
|load:               True                                              |
|load_quiet:         True                                              |
|min_neighbour_dist: 0.01                                              |
|move_tol:           0.3                                               |
|num_lines:          11                                                |
|pos_tol:            0.01                                              |
|save_file:          ./results/res_0.p                                 |
|serializer:         auto                                              |
|surface:            <function <lambda> at 0x7fb453d6d950>             |
|system:             <z2pack.fp._first_prin<...>ject at 0x7fb453c472b0>|
+----------------------------------------------------------------------+

INFO: Adding lines required by 'num_lines'.
INFO: Adding line at t = 0.0
INFO:       Calculating line for N = 8
/bin/sh: 1: Syntax error: Bad fd number
Traceback (most recent call last):
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/fp/_read_mmn.py", line 16, in get_m
FileNotFoundError: [Errno 2] No such file or directory: '/home/dennis/Z2Pack/examples/fp/Bi_vasp/build/wannier90.mmn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 34, in <module>
    load=True
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 149, in run_surface
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 277, in _run_surface_impl
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 221, in add_line
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 194, in get_line
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/line/_run.py", line 202, in _run_line_impl
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/fp/_first_principles.py", line 138, in get_mmn
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/fp/_read_mmn.py", line 56, in get_m
FileNotFoundError: [Errno 2] No such file or directory: '/home/dennis/Z2Pack/examples/fp/Bi_vasp/build/wannier90.mmn'. Check that the path of the .mmn file is correct (mmn_path input variable). If that is the case, an error occured during the call to the first-principles code and Wannier90. Check the corresponding log/error files.

I have also tried generating the 'wannier90.mmn’ file separately (by running a vasp_ncl calculation based on the input files provided in the example and the GGA flavor of POTCAR for Bi) and including it as an input variable to the script, i.e. 

system = z2pack.fp.System(
    input_files=["input/wannier90.mmn","input/CHGCAR", "input/INCAR", "input/POSCAR", "input/POTCAR", "input/wannier90.win" ],
    kpt_fct=z2pack.fp.kpoint.vasp,
    kpt_path="KPOINTS",
    command="mpirun $VASP >& log"
)

For which the following error is produced, 

+----------------------------------------------------------------------+
|===================                                                   |
|SURFACE CALCULATION                                                   |
|===================                                                   |
|starting at 2018-12-14 15:22:37,034                                   |
|running Z2Pack version 2.1.1                                          |
|                                                                      |
|gap_tol:            0.3                                               |
|init_result:        None                                              |
|iterator:           range(8, 27, 2)                                   |
|load:               True                                              |
|load_quiet:         True                                              |
|min_neighbour_dist: 0.01                                              |
|move_tol:           0.3                                               |
|num_lines:          11                                                |
|pos_tol:            0.01                                              |
|save_file:          ./results/res_0.p                                 |
|serializer:         auto                                              |
|surface:            <function <lambda> at 0x7f7c07216950>             |
|system:             <z2pack.fp._first_prin<...>ject at 0x7f7c070f02b0>|
+----------------------------------------------------------------------+

INFO: Adding lines required by 'num_lines'.
INFO: Adding line at t = 0.0
INFO:       Calculating line for N = 8
/bin/sh: 1: Syntax error: Bad fd number
Traceback (most recent call last):
  File "run.py", line 34, in <module>
    load=True
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 149, in run_surface
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 277, in _run_surface_impl
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 221, in add_line
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/surface/_run.py", line 194, in get_line
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/line/_run.py", line 202, in _run_line_impl
  File "/home/dennis/.local/lib/python3.5/site-packages/z2pack-2.1.1-py3.5.egg/z2pack/fp/_first_principles.py", line 142, in get_mmn
ValueError: The number of overlap matrices found is 4, but should be 7. Maybe check search_shells in wannier90.win

Please let me know if you know of any solution to this problem. I am still trying to debug it myself but any help you can give is deeply appreciated!

**Comment by dptru10** [comment]
I progressed in getting the tutorial to run by changing the '$VASP' variable to an actual path instead of treating it like a bash environment variable.

**Comment by greschd** [comment]
Is there still an error, or can I close this issue?

**Comment by dptru10** [comment]
The issue can be closed. Thanks for the quick response. 

Thanks,
-Dennis

**Comment by surasree1812** [comment]
I am getting the same error. How do you solve it?

**Comment by greschd** [comment]
If I understood it correctly, @dptru10 solved it by replacing `$VASP` with the path to the VASP executable in the `command` keyword argument.
