### ISSUE TITLE
Error when using built-in kpoints function for VASP

### ISSUE THREAD

**Issue by jkidd1** [Z2PackDev/Z2Pack#86]
I am trying to do a Chern number calculation using VASP. I have tested my build of the modified VASP+W90 by following the tutorials (Bi, WTe2, and Bi2Se3 all produce the expected result). Here is the relevant portion of my run.py file:

system = z2pack.fp.System(
    input_files=["inputs/INCAR", "inputs/POSCAR", "inputs/POTCAR","inputs/wannier90.win"],
    kpt_fct=z2pack.fp.kpoint.vasp,
    kpt_path="KPOINTS",
    command="mpirun /home/jkidd/repos/zmod2/vasp.5.4.4/bin/vasp_std >& result.v2w90"
)

result = z2pack.surface.run(
    system=system,
    surface=z2pack.shape.Sphere(center=[0.0, 0.0, 0.28125], radius=0.1),
    save_file='./results/res_0.p',
    load=True,
)

When I run the script, I get the first "Calculating line for N = 8", then immediately get the following error:

Traceback (most recent call last):
  File "./run.py", line 31, in <module>
    iterator=range(10, 50, 5)
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/surface/_run.py", line 149, in run_surface
    serializer=serializer
  File "/home/jkidd/miniconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/surface/_run.py", line 277, in _run_surface_impl
    result = add_line(t)
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/surface/_run.py", line 221, in add_line
    data.add_line(t, get_line(t))
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/surface/_run.py", line 194, in get_line
    init_result=init_line_result
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/line/_run.py", line 202, in _run_line_impl
    list(np.array(line(k)) for k in np.linspace(0., 1., run_options['num_steps']))
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/fp/_first_principles.py", line 127, in get_mmn
    self._create_input(kpt)
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/fp/_first_principles.py", line 121, in _create_input
    f.write(self._kpt_fct[i](kpt))
  File "</home/jkidd/miniconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-32>", line 2, in vasp
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/fp/kpoint.py", line 33, in _check_dim
    return fct(kpt)
  File "</home/jkidd/miniconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-31>", line 2, in vasp
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/fp/kpoint.py", line 41, in _check_closed
    return fct(kpt)
  File "/home/jkidd/.local/lib/python3.7/site-packages/z2pack/fp/kpoint.py", line 171, in vasp
    raise ValueError('The k-points can change only in kx-, ky- or kz direction for VASP runs. The given k-points change in {} directions.'.format(len(nonzero)))
ValueError: The k-points can change only in kx-, ky- or kz direction for VASP runs. The given k-points change in 0 directions.

It's definitely not a VASP or W90 issue, so I'm not sure what to make of it. Any help would be much appreciated.

**Comment by greschd** [comment]
This error is intentional: Because the VASP to Wannier90 interface (at least last I checked) supports only regular grids, it is impossible to compute the overlap matrices on a sphere with VASP. The only code you can do that with currently is Quantum Espresso.

If the VASP - Wannier interface was updated recently this might no longer be true, in which case a new "k-point writing" function would need to be implemented to make use of it.

**Comment by jkidd1** [comment]
Dominik, thank you for the incredibly fast response. I'm new to both VASP and Z2Pack, and I completely overlooked this restriction on the k-point grids in VASP. And as far as I know, VASP has still not updated the interface to Wannier90.

**Comment by greschd** [comment]
You're welcome! I'll close this issue, then.
